### ISSUE TITLE
Need Help 

### ISSUE THREAD

**Issue by ankit-trantor** [amanjeetsingh150/UberCarAnimation#2]
Hello can u tell me how i rotate car on given path according to driver location.Suppose i have to go to Source A to Destination B.Route i got from direction api .Driver lat long also on same starting position i want to navigate driver car according to lat long of route api.

**Comment by amanjeetsingh150** [comment]
Get the bearing at every point and turn accordingly. I hope our conversation cleared your doubts.
Do tell me if u had any more.
Thanks :+1:
