### ISSUE TITLE
error_message	"The provided API key is invalid."

### ISSUE THREAD

**Issue by asifali9145** [amanjeetsingh150/UberCarAnimation#5]
I am using my own google maps api key and i got following error_message 
"The provided API key is invalid."
How i resolved this issue?

**Comment by amanjeetsingh150** [comment]
Hey @asifali9145 you have to generate your own key of maps and google directions key. Are you doing it and using them correctly?

**Comment by amanjeetsingh150** [comment]
I am closing this issue as it has been in active for quite a while and there are no responses feel free to reopen and tell me the issue.

Thanks :+1:
