### ISSUE TITLE
Callback when location reached

### ISSUE THREAD

**Issue by adnanafzal565** [amanjeetsingh150/UberCarAnimation#7]
Thank you for your great project.

I wanted to ask how can I know when the car reaches its destination ? Can we get any callback listener for that ?

Thanks.

**Comment by amanjeetsingh150** [comment]
Hey @adnanafzal565 yes that can be done will update the project accordingly. Until that time if you want I can explain through code snippets here only?

**Comment by adnanafzal565** [comment]
yes, that would be great. a little explanation would help.

**Comment by amanjeetsingh150** [comment]
Hey @adnanafzal565 I have updated the code. I have created my own Event Bus for this Purpose it can be shifted in any part of your code to receive updates.
1. Journey Begin Event
2. Journey End Event
3. Current location update

Do check and revert :+1: 
As it is solved I am closing the issue. Feel free to reopen if anything seems wrong on your side.

**Comment by adnanafzal565** [comment]
Great. Thanks a lot. It is really an amazing library.
